services:
  waha:
    image: devlikeapro/waha:latest
    ports:
      - '3001:3000'
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_PRINT_QR=True
      - WAHA_SESSION_STORE=FILE
    volumes:
      - ./.waha:/app/.sessions
